# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PostHandler' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PostHandler
      pod 'SwiftLint'

  target 'PostHandlerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PostHandlerUITests' do
    # Pods for testing
  end

end
